### PR TITLE
Richer popover on wot score in notes

### PR DESCRIPTION
**Pull request by ticruz38**
A richer popover information as proposed in #385

https://github.com/user-attachments/assets/c16f843d-e4e4-4610-abb2-1ff4bed86db3

### CODE REVIEW

**Comment by staab** [comment]
Looks good, maybe bold the username and fade the pubkey. We don't need the previous username stuff right now, although "since" might be useful for tracking the last time the kind 0 was updated (even though the username won't necessarily have changed)

**Comment by ticruz38** [comment]
With faded pubkey, bold username, and last profile update.

https://github.com/user-attachments/assets/d31b47ac-9388-4422-92b9-892b57ba5586

**Comment by staab** [comment]
Couple things on testing:

- [ ] Make the `i` icon clickable as well
- [ ] Make the person's name clickable, bringing the user to the profile page

**Comment by ticruz38** [comment]
User name and wot `i` tag are now link to their respective "detail" page

Yes it is ready to merge, it's just a new component, WotPopover, most of the code change is there.

**Comment by staab** [comment]
Merged via rebase locallly

**Pull request closed without merging**
